### ISSUE TITLE
in-repo-engine blueprint doesn't work on ember-cli 2.6.1

### ISSUE THREAD

**Issue by nucleartide** [dgeb/ember-engines#141]
On ember-engines 0.2.5, running the command `ember g in-repo-engine test-engine` will produce the following error:

```
Cannot find module 'ember-cli/blueprints/route/index'
Error: Cannot find module 'ember-cli/blueprints/route/index'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jason/Repositories/ember-defaults/node_modules/ember-engines/blueprints/in-repo-engine/index.js:5:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

I'm not entirely sure why ember-cli decided to [remove a bunch of blueprints after v2.5.0][1]...

[1]: https://github.com/ember-cli/ember-cli/tree/v2.6.1/blueprints

**Comment by knownasilya** [comment]
They got moved to the ember.js repo, since ember-cli is used by other projects like angular.

**Comment by mike-north** [comment]
**Workaround:** Use ember-cli 2.5

```sh
rm -rf node_modules/ember-cli && \
  npm install --save-dev ember-cli@2.5
```

**Comment by dgeb** [comment]
Fixed via #147 and then #151
