### ISSUE TITLE
"`_generatePackageJson` is not a function" error with in-repo-engine blueprint

### ISSUE THREAD

**Issue by mixonic** [dgeb/ember-engines#238]
Can't seem to create a new `in-repo-addon`

```
[Projects] ember new get-lazy
[Projects] cd get-lazy/
[get-lazy] npm i && bower i
[get-lazy] npm i --save-dev ember-engines@0.4.0-beta.1
[get-lazy] ember g in-repo-engine admin
installing in-repo-engine
installing lib
  create lib/.jshintrc
  create lib/admin/addon/engine.js
  create lib/admin/addon/routes.js
  create lib/admin/addon/templates/application.hbs
  create lib/admin/config/environment.js
  create lib/admin/index.js
  create lib/admin/package.json
this._generatePackageJson is not a function
TypeError: this._generatePackageJson is not a function
    at CoreObject.afterInstall (/Users/mixonic/Projects/get-lazy/node_modules/ember-cli/blueprints/in-repo-addon/index.js:21:10)
    at CoreObject.afterInstall (/Users/mixonic/Projects/get-lazy/node_modules/ember-engines/blueprints/in-repo-engine/index.js:68:30)
    at tryCatch (/Users/mixonic/Projects/get-lazy/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/mixonic/Projects/get-lazy/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/mixonic/Projects/get-lazy/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/mixonic/Projects/get-lazy/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Confirmed this is only in 0.4.1-beta.1, generation works with 0.3.4.

**Comment by trentmwillis** [comment]
I think we just need to port this forward: https://github.com/dgeb/ember-engines/pull/219. Will test it out and see.
